server:
  port: 8080

eureka:
  instance:
    instance-id: front-api
    hostname: localhost
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:1234@localhost:8761/eureka
