server:
  port: 8081

eureka:
  instance:
    instance-id: front-api
    hostname: localhost
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:1234@eureka-server:8761/eureka


